### Get all
GET http://localhost:8080/api/adrese/all

### Get one by id
GET http://localhost:8080/api/adrese/find/1

### Create
POST http://localhost:8080/api/adrese/create
Content-Type: application/json

{
  "drzava": "",
  "mesto": "",
  "ulica": "",
  "broj": 0
}